apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: holamundo-web
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/cronosDevs/argoCD.git'
    targetRevision: HEAD
    path: manifest
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
